In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
file_path = r"C:\Users\user\Downloads\Data_for_UCI_named.csv"
elect = pd.read_csv(file_path)

In [3]:
elect.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
elect.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [5]:
elect.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [6]:
elect.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [7]:
elect = pd.get_dummies(elect, columns = ["stabf"], drop_first = True)

In [8]:
elect = elect.drop(columns = "stab")

In [9]:
elect.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4  stabf_unstable  
0 -1.723086  0.650456  0.859578  0.887445  0.958034               1  
1 -1.255012  0.413441  0.862414  0.562139  0.781760               0  
2 -0.920492  0.163041  0.766689  0.839444  0.109853               1  
3 -0.997374  0.446209  0.976744  0.929381  0.362718               1  
4 -0.554305  0.797110  0.455450  0.656947  0.820923               1

In [10]:
elect = elect.rename({"stabf_unstable":"stabf"}, axis = 1)
elect.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4  stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034      1  
1 -1.255012  0.413441  0.862414  0.562139  0.781760      0  
2 -0.920492  0.163041  0.766689  0.839444  0.109853      1  
3 -0.997374  0.446209  0.976744  0.929381  0.362718      1  
4 -0.554305  0.797110  0.455450  0.656947  0.820923      1

In [11]:
elect["stabf"].value_counts()

1    6380
0    3620
Name: stabf, dtype: int64

In [12]:
X = elect[[i for i in elect.columns if i != "stabf"]]
y = elect["stabf"]

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns = X.columns)

In [14]:
X_scaled.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0 -0.835374 -0.791317  1.141704  1.652103  0.017397  1.079405 -0.017078   
1  1.478297 -0.126705 -0.803111 -1.415043  1.752124 -1.593619 -1.438158   
2  1.357093  1.312140 -0.803499 -1.471504 -0.458492  0.098253 -0.062840   
3 -1.653138  0.882289 -0.278354 -1.060901  0.284250  0.513904 -1.591046   
4 -0.771543  0.860108 -0.111670  1.680114 -0.298075  0.287450 -1.376343   

         p4        g1        g2        g3        g4  
0 -1.092545  0.457467  1.220013  1.321628  1.579026  
1 -0.011575 -0.406791  1.230354  0.135424  0.936256  
2  0.760963 -1.319852  0.881299  1.146596 -1.513802  
3  0.583414 -0.287304  1.647250  1.474543 -0.591750  
4  1.606636  0.992226 -0.253610  0.481133  1.079063

In [15]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 1)

### Random Forest Classifier

In [38]:
from sklearn.ensemble import RandomForestClassifier
parameters = {"n_estimators": [50, 100, 300, 500, 1000],
              "min_samples_split" : [2, 3, 5, 7, 9],
              "min_samples_leaf" : [1, 2, 4, 6, 8],
              "max_features" : ['auto', 'sqrt', 'log2', None]}

radn_search = RandomizedSearchCV(RandomForestClassifier(), param_distributions = parameters, scoring = "accuracy",
                                 cv = 5, random_state = 1, n_jobs = -1)
radn_search.fit(X_train,y_train)
radn_search.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 4,
 'max_features': 'log2'}

In [39]:
predis = radn_search.best_estimator_.predict(X_test)
print(accuracy_score(y_test, predis))

0.9235


In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, matthews_corrcoef
model_1 = RandomForestClassifier(random_state = 1)
model_1.fit(X_train, y_train)
pred_1 = model_1.predict(X_test)

print(accuracy_score(y_test, pred_1))

print(confusion_matrix(y_test, pred_1))

print(classification_report(y_test, pred_1))

print(matthews_corrcoef(y_test,pred_1))

0.929
[[ 625   87]
 [  55 1233]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       712
           1       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000

0.8441093203498148


### ExtraTrees Classifier

In [35]:
parameters = {"min_samples_split" : [2, 3, 5, 7, 9],
              "min_samples_leaf" : [1, 2, 4, 6, 8],
              "max_features" : ['auto', 'sqrt', 'log2', None]}

ExtraTree_search = RandomizedSearchCV(ExtraTreeClassifier(random_state = 1), param_distributions = parameters, scoring = "accuracy",
                                 cv = 5, random_state = 1, n_jobs = -1,n_iter = 10, verbose = 1)
ExtraTree_search.fit(X_train,y_train)
ExtraTree_search.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


{'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}

In [36]:
prediction_Extra_Tree = ExtraTree_search.best_estimator_.predict(X_test)
print(accuracy_score(y_test, prediction_Extra_Tree))

0.83


In [44]:
from sklearn.tree import ExtraTreeClassifier
model_2 = ExtraTreeClassifier(random_state = 1)
model_2.fit(X_train, y_train)
pred_2 = model_2.predict(X_test)

print(accuracy_score(y_test, pred_2))

print(confusion_matrix(y_test, pred_2))

print(classification_report(y_test, pred_2))

print(matthews_corrcoef(y_test,pred_2))

0.751
[[ 465  247]
 [ 251 1037]]
              precision    recall  f1-score   support

           0       0.65      0.65      0.65       712
           1       0.81      0.81      0.81      1288

    accuracy                           0.75      2000
   macro avg       0.73      0.73      0.73      2000
weighted avg       0.75      0.75      0.75      2000

0.4576435701875208


In [43]:
tree_scores = pd.Series(ExtraTree_search.best_estimator_.feature_importances_, index = X.columns)
tree_scores.nlargest(12).index

Index(['tau3', 'tau1', 'tau4', 'tau2', 'g4', 'g2', 'g1', 'g3', 'p4', 'p3',
       'p1', 'p2'],
      dtype='object')

### XGBOOST Model

In [47]:
import xgboost as xgb
Xgboost = xgb.XGBClassifier()

In [48]:
import warnings
warnings.filterwarnings("ignore")
parameters = {"n_estimators": [50, 100, 300, 500, 1000],
              "min_samples_split" : [2, 3, 5, 7, 9],
              "min_samples_leaf" : [1, 2, 4, 6, 8],
              "max_features" : ['auto', 'sqrt', 'log2', None]}

xgboost_search = RandomizedSearchCV(xgb.XGBClassifier(), param_distributions = parameters, scoring = "accuracy",
                                 cv = 5, random_state = 1, n_jobs = -1, )
xgboost_search.fit(X_train,y_train)
xgboost_search.best_params_

[21:27:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:573: 
Parameters: { "max_features", "min_samples_leaf", "min_samples_split" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[21:27:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 4,
 'max_features': 'log2'}

In [49]:
Xgboost = xgb.XGBClassifier(random_state = 1, eval_metric = "error")
Xgboost.fit(X_train, y_train)

pred_xgb = Xgboost.predict(X_test)

print(accuracy_score(y_test, pred_xgb))

print(confusion_matrix(y_test, pred_xgb))

print(classification_report(y_test, pred_xgb)

print(matthews_corrcoef(y_test,pred_xgb))

SyntaxError: invalid syntax (<ipython-input-49-4e186e3a72be>, line 12)

### LightGBM Model

In [32]:
import lightgbm as  lgb

In [45]:
lgbm = lgb.LGBMClassifier(random_state = 1)
lgbm.fit(X_train, y_train)

pred_lgbm = lgbm.predict(X_test)

print(accuracy_score(y_test, pred_lgbm))

print(confusion_matrix(y_test, pred_lgbm))

print(classification_report(y_test, pred_lgbm))

print(matthews_corrcoef(y_test,pred_lgbm))

0.94
[[ 644   68]
 [  52 1236]]
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       712
           1       0.95      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000

0.8686192100585107
